name: Trigger Gatsby Cloud Build
on:
  schedule:
    - cron: "0 13 * * *" # every day at 13:00 UTC (i.e. 8:00 AM EST)
jobs:
  build:
    name: Request Gatsby Cloud Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://webhook.gatsbyjs.com/hooks/data_source/publish/4c261bab-d94a-44d2-ac23-3d16a96fa29e
